### ISSUE TITLE
[BUG] rollover abort 20 hours before rollover.

### ISSUE THREAD

**Issue by BadHorseMonkey** [loathers/garbage-collector#1721]
**Describe the bug**
New rollover abort code aborted with 72325 seconds until rollover.

**To Reproduce**
I dunno.  Adventure with 72325 seconds until rollover.

**Expected behavior**
A longer window for adventuring.
**Session Log**

[Mad_Carew_20231109.txt](https://github.com/loathers/garbage-collector/files/13305118/Mad_Carew_20231109.txt)

**Comment by xn** [comment]
From the docs:
https://wiki.kolmafia.us/index.php/Rollover

```if (rollover() - now_to_int() > 0) {
   print("There are " + (rollover() - now_to_int()) + " seconds until rollover.");
} else {
   print("Rollover is now.");
}```
It appears `rollover()` is returning seconds.
It seems like `safeInterrupt()` thinks it is returning microseconds?
```
rollover() * 1000 - Date.now()
```
https://github.com/loathers/garbage-collector/blob/main/packages/garbo/src/lib.ts#L173

**Comment by xn** [comment]
I'm still getting this error. I thought the recent fix was off and tried to "fix" it, but I misread the code and at the end of it wrote code that was functionally equivalent to the fix. 🙃 Anyways, I had to hack that bit out of my local copy of garbo to get it to run. Won't have time to triage it till the weekend.

**Comment by horrible-little-slime** [comment]
`safeInterrupt` thinks it is returning seconds, which is why it mulitplies by 1000, to convert it into milliseconds, to be consistent with `Date.now()`

This should be resolved by #1719

**Comment by xn** [comment]
FWIW, I was still getting this error this morning (7am Eastern) even with the updated code in 1719.
