### ISSUE TITLE
[BUG] Garbo attempting to use Spring Shoes - I don't have them unboxed

### ISSUE THREAD

**Issue by wetflame** [loathers/garbage-collector#1871]
**Describe the bug**

Garbo appears to be trying to use the spring shoes when I don't have them unboxed.  

**To Reproduce**

Ran the command "garbo ascend -65 workshed=trainset nodiet"

**Session Log**
Attach a full KoLMafia session log from the day you encountered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.

 I'm getting this error:

`JavaScript exception: Combat exception! Last macro error: Too many, or zero, matches for skill, "Spring Away", macro aborted.. Exception KoLmafia error: You're on your own, partner. (Too many, or zero, matches for skill, "Spring Away", macro aborted.). (file:/.../scripts/garbage-collector/garbo.js#40748)
`

**Additional context**
I haven't used mafia for a week as I've been away so this appears to have been introduced between the 25th April and now.

Session Log:
[King_Dave_20231031.txt](https://github.com/loathers/garbage-collector/files/15198574/King_Dave_20231031.txt)

**Comment by biancaleeyx** [comment]
I've had the same issue on an alt without Spring Shoes starting today, with newest mafia (27922) and git updated. It did not happen yesterday.

**Comment by Tapionator** [comment]
Same as well. Alt doesn't have the shoes, had to use older version of garbo in the meantime.

**Comment by SalMonella01** [comment]
The same.  The alt in question has no Spring Shoes or skill called Spring Away.

**Comment by Shad0** [comment]
Ditto. I don't have the Spring Shoes, but for the past few days I've been consistently getting this same error message:

> JavaScript exception: Combat exception! Last macro error: Too many, or zero, matches for skill, "Spring Away", macro aborted.. Exception KoLmafia error: You're on your own, partner. (Too many, or zero, matches for skill, "Spring Away", macro aborted.). 

I wonder if it's possible that fix #1866 somehow convinced garbo that, as long as we don't have Everything Looks Green, then we must be able to use the Spring Shoes even if we don't actually own them?

**Comment by Malibu-Stacey** [comment]
This has been fixed in [Libram](https://github.com/loathers/libram/pull/611) but garbo hasn't been rebuilt with that change yet.

**Comment by SalMonella01** [comment]
I still see the same exact problem.  Don't y'all have a test box that *doesn't* have Spring Shoes?
This is with Mafia r27935, garbo Local Version: f43f35c07cf63f656cfc8e9b0fb08834b4653cfd (built from main@e2846901bb41fbd33d5295ec03f5c660bb373a97)

**Comment by Tapionator** [comment]
Same on my end as well, Garbo is updated as well.

**Comment by gausie** [comment]
> Don't y'all have a test box that _doesn't_ have Spring Shoes?

Please be polite.

**Comment by Shad0** [comment]
Ditto on the problem, and also we really _really_ appreciate everyone who _donates their time_ to work on this _for free_

**Comment by SalMonella01** [comment]
Trying to be as polite and inoffensive as it is possible for me to be...
Was the fix tested before the bug report was closed?  If so, how did the tester get it to work?

**Comment by gausie** [comment]
> Trying to be as polite and inoffensive as it is possible for me to be... 

Try harder.

**Comment by SalMonella01** [comment]
Yay!  It works now!

**Comment by Shad0** [comment]
Confirmed! Many thanks!
