### ISSUE TITLE
Tries Spring Away without the Spring Shoes

### ISSUE THREAD

**Issue by Gawea1** [loathers/garbage-collector#1885]
Garbo seems to be calling a spring shoes skill even though I don't have spring shoes. Garbo works again when I comment out lines 5212 to 5220 (//Free unlimited source).

**Expected behavior**
No abort.

**Session Log**
Round 2: You gain 28 Mojo Points
Round 2: You lose 1 hit point
Preference lastMacroError changed from Macro Aborted: 37 instructions (In a row?!) executed without any actions being taken. to Too many, or zero, matches for skill, "Spring Away", macro aborted.
You're on your own, partner. (Too many, or zero, matches for skill, "Spring Away", macro aborted.)
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)

You are currently in a fight.
You are currently in a fight.
Preference customCombatScript changed from garbo to default
CCS set to default
autoSatisfyWithStash => true
Preference autoSatisfyWithStash changed from false to true
hpAutoRecovery => 0.15
Preference hpAutoRecovery changed from -0.05 to 0.15
hpAutoRecoveryTarget => 0.8
Preference hpAutoRecoveryTarget changed from 0.0 to 0.8
mpAutoRecovery => 0.15
Preference mpAutoRecovery changed from -0.05 to 0.15
mpAutoRecoveryTarget => 0.95
Preference mpAutoRecoveryTarget changed from 0.0 to 0.95
afterAdventureScript => postadventure.ash
Preference afterAdventureScript changed from to postadventure.ash
counterScript => CounterChecker.ash
Preference counterScript changed from to CounterChecker.ash
currentMood => default
Preference currentMood changed from apathetic to default
valueOfInventory => 2
Preference valueOfInventory changed from 2.0 to 2
Preference choiceAdventure1387 changed from 2 to -1
Encounter: horrible tourist family
You are currently in a fight.
You fought 0 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
Including this, you have fought 0 across all ascensions today
Preference garboResultsDate changed from 20240509 to 20240511
Preference garboResultsMeat changed from 2693024 to 0
Preference garboResultsItems changed from 1916721 to 0
Preference garboResultsTurns changed from 281 to 0
Extreme Items:
9 handful of barley worth 78570 total
1 Volcoino worth 59666 total
9 cluster of hops worth 36450 total
-1 extra time worth -29700 total
-5 pulled blue taffy worth -18900 total
-3 chocolate stolen accordion worth -14820 total
Preference garboResultsMeat changed from 0 to -76420
Preference garboResultsItems changed from 0 to 269855
This run of garbo, across 0 turns you generated 193,435 meat, with -76,420 raw meat and 269,855 from items
So far today, across 0 turns you generated 193,435 meat, with -76,420 raw meat and 269,855 from items
JavaScript exception: Combat exception! Last macro error: Too many, or zero, matches for skill, "Spring Away", macro aborted.. Exception Combat exception! Last macro error: Too many, or zero, matches for skill, "Spring Away", macro aborted.. Exception KoLmafia error: You're on your own, partner. (Too many, or zero, matches for skill, "Spring Away", macro aborted.).. (file:/D:/KoLMafia/scripts/garbage-collector/garbo.js#43729)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:43729 (f)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:45061
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:41282 (withStash)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:45051 (freeRunFights)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:45089 (freeFights)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:49854
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:41303 (withClan)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:41297 (withVIPClan)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:49835
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:41282 (withStash)
at file:/D:/KoLMafia/scripts/garbage-collector/garbo.js:49834 (main)
You are currently in a fight.
You are now in away mode, chat will update more slowly until you say something.

**Comment by Arashmin** [comment]
Reporting in, I am getting the same issue, and I do in fact have spring shoes in my inventory.  Just that the script isn't equipping them.

**Comment by horrible-little-slime** [comment]
Resolved in latest release

**Comment by Arashmin** [comment]
Seems I'm still getting this issue, even after a full git delete of garbo (or whatever git list called it) and pulling again.

[Arashmin_20240513.txt](https://github.com/loathers/garbage-collector/files/15289600/Arashmin_20240513.txt)

Relevant session log snippet:

[382] Noob Cave
Preference lastEncounter changed from garbage tourist to Teacher's Pet
Encounter: Teacher's Pet
Took choice 1470/4: Do nothing
choice.php?whichchoice=1470&option=4&pwd
Preference juneCleaverQueue changed from 1468,1473,1474,1475,1469,1467 to 1473,1474,1475,1469,1467,1470
Preference _juneCleaverSkips changed from 1 to 2
Preference _juneCleaverFightsLeft changed from 0 to 8
Preference recoveryScript changed from  to Universal_recovery
> 
> Executing Wanderers/Spring Shoes Freerun
> Wandering at The Haunted Kitchen for expected value 0.00 (Default)
Preference logPreferenceChangeFilter changed from _lastCombatStarted,libram_savedMacro,maximizerMRUList,testudinalTeachings to garboEmbezzlerCount,garboEmbezzlerDate,garboEmbezzlerSources,libram_savedMacro,maximizerMRUList,spadingData,testudinalTeachings
Preference hpAutoRecoveryTarget changed from 0.0 to 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
Preference choiceAdventure1468 changed from 4 to 2
Preference choiceAdventure1470 changed from 4 to 2
Preference choiceAdventure1472 changed from 4 to 1
Preference logPreferenceChange changed from true to false

use 1 Peppermint Pip Packet
You acquire an item: packet of tall grass seeds
> You fought 0 Knob Goblin Embezzler at the beginning of the day, and an additional 1 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
> Including this, you have fought 91 across all ascensions today
> Extreme Items:
> 1 pocket wish worth 44820 total
> 2 flapper fly worth 16015 total
> 2 Coinspiracy worth 14084 total
> 1 garbage juice slurpee worth 5 total
> 1 embezzler's oil worth 5 total
> 1 stick of &quot;gum&quot; worth 5 total
> This run of garbo, across 30 turns you generated 334,947 meat, with 198,016 raw meat and 136,931 from items
> So far today, across 126 turns you generated 3,711,365 meat, with 2,806,247 raw meat and 905,118 from items
mallsearch "haunted doghouse"
mallsearch "Witchess Set"
mallsearch "Source terminal"
> Warning: Insufficient turns were run, so this estimate is subject to large variance. Be careful when using these values as is.
> Marginal MPA: NaN [raw] + NaN [items] = NaN [total]

Closing session for Arashmin...
